# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop/dev branch
on:
  push:
    branches: main
#   pull_request:
#     branches: [ develop/dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.TOKEN }}
          ARGS: '-avzr --delete'
          SOURCE: '/pixel-art/dist/'
          REMOTE_HOST: ${{ secrets.HOST_NAME }}
          REMOTE_USER: 'root'
          TARGET: '/var/www/pixel-server'
        run:
      - name: Server Start    
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.HOST_NAME }}
              username: 'root'
              key: ${{ secrets.TOKEN }}
              script: |
                pm2 start --name pixel-art /var/www/pixel-server/main.js
                echo pm2 run success